#!/bin/env bash
#PBS -l walltime=4:00:00
#PBS -l nodes=1:ppn=1
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m aeb
#PBS -A lp_joris_vermeesch_c1

#merge raw fastq files together

nanopore_dir="/lustre1/project/stg_00019/Nanopore_GC_Data"
workdir="/lustre1/project/stg_00019/research/yan/nanopore_data/2_sc_PTA"
outdir=$workdir/1_merged_fastq
mkdir -p $outdir

sample="HG002_sc_PTA"

small_fastq_1="$nanopore_dir/PAI76636_14032022_GP_WGA_Bio_sc/20220314_1346_1F_PAI76636_e5400800/fastq_pass"
small_fastq_2="$nanopore_dir/PAI76636_14032022_WGA_Bio_sc_2/20220314_1737_1G_PAI76636_009ccffc/fastq_pass"
small_fastq_3="$nanopore_dir/PAI74477_GP_WGA_Bio_sc_3/20220315_1653_2B_PAI74477_683940d5/fastq_pass"


cat $small_fastq_1/PAI76636_pass_64db3016_*.fastq.gz > $outdir/$sample.1.fastq.gz
cat $small_fastq_2/PAI76636_pass_69ce86c3_*.fastq.gz > $outdir/$sample.2.fastq.gz
cat $small_fastq_3/PAI74477_pass_a38c7ec9_*.fastq.gz > $outdir/$sample.3.fastq.gz

cat $outdir/$sample.?.fastq.gz > $outdir/$sample.fastq.gz

# check for the number of reads:

zcat $outdir/$sample.1.fastq.gz | wc | awk '{print "HG002_sc_PTA_1_read_count\t"$1/4}'>$outdir/HG002_sc_PTA_read_count.txt
zcat $outdir/$sample.2.fastq.gz | wc | awk '{print "HG002_sc_PTA_2_read_count\t"$1/4}'>>$outdir/HG002_sc_PTA_read_count.txt
zcat $outdir/$sample.3.fastq.gz | wc | awk '{print "HG002_sc_PTA_3_read_count\t"$1/4}'>>$outdir/HG002_sc_PTA_read_count.txt

zcat $outdir/$sample.fastq.gz | wc | awk '{print "HG002_sc_PTA_read_count\t"$1/4}'>>$outdir/HG002_sc_PTA_read_count.txt