#!/bin/bash -l
#PBS -l walltime=4:00:00
#PBS -l mem=10gb
#PBS -l nodes=1:ppn=2
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m eab
#PBS -A lp_joris_vermeesch_c1


##[HELP] This tool will create a qc report of the fastq files
##[HELP] This script is multithreaded
##[HELP] This script runs between 1 and 10 minutes per fastq file
##
##[HOWTO] #FASTQC
##[HOWTO] #start the module:
##[HOWTO] qsub 4_fastqc_new.pbs

#setting all parameters (these could be changed)
PROJECT_DIR="/lustre1/project/stg_00019/research/yan/nanopore_data/sc_repli-g";
SAMPLE_DIR="$PROJECT_DIR/3_nanofilt_trimmed";
OUTPUT_DIR="$PROJECT_DIR/4_fastqc_new";
mkdir -p $OUTPUT_DIR;

cd $SAMPLE_DIR;
file=`ls *.fastq.gz`

module load FastQC/0.11.8-Java-1.8.0_162

fastqc -o $OUTPUT_DIR -t 15 $file;

