#!/bin/bash -l
#PBS -l walltime=4:00:00
#PBS -l mem=10gb
#PBS -l nodes=1:ppn=2
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m eab
#PBS -A lp_joris_vermeesch_c1

module load Python/3.7.2-foss-2018a  

PROJECT_DIR="/lustre1/project/stg_00019/research/yan/nanopore_data/2_sc_PTA";
SAMPLE_DIR="$PROJECT_DIR/1_merged_fastq";
OUTPUT_DIR="$PROJECT_DIR/2_nanoplot_fastq_raw";
mkdir -p $OUTPUT_DIR;
SAMPLE="HG002_sc_PTA"

conda activate nanoplot

NanoPlot --fastq $SAMPLE_DIR/$SAMPLE.fastq.gz \
    -o $OUTPUT_DIR \
    -t 18