#!/bin/bash -l
#PBS -l walltime=3:00:00
#PBS -l mem=30gb
#PBS -l nodes=1:ppn=6
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m eab
#PBS -A lp_joris_vermeesch_c1

module load Python/3.7.2-foss-2018a  

PROJECT_DIR="/lustre1/project/stg_00019/research/yan/nanopore_data/2_sc_PTA";
SAMPLE_DIR="$PROJECT_DIR/5_mapped";
OUTPUT_DIR="$PROJECT_DIR/5_nanoplot_bam";
mkdir -p $OUTPUT_DIR;

conda activate nanoplot

bam=`ls $SAMPLE_DIR/*.trimmed.sorted.bam`

NanoPlot --bam $bam \
    -o $OUTPUT_DIR \
    -t 18