#!/bin/bash -l
#PBS -l walltime=5:00:00
#PBS -l mem=60gb
#PBS -l nodes=1:ppn=12
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m eab
#PBS -A lp_joris_vermeesch_c1

module load SAMtools/1.9-GCC-6.4.0-2.28

file=/lustre1/project/stg_00019/research/yan/nanopore_data/sc_repli-g/5_mapped/HG002_sc.trimmed.sorted.bam 

echo total_supplementary_alignmet
samtools view -f 2048 $file|wc -l
echo the_flags_of_supplementary_alignmets
samtools view -f 2048 $file|awk '{print $2}'|sort|uniq



