#!/bin/bash -l
#PBS -l walltime=15:00:00
#PBS -l mem=60gb
#PBS -l nodes=1:ppn=12
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m eab
#PBS -A lp_joris_vermeesch_c1

module load SAMtools/1.9-GCC-6.4.0-2.28

# change sam flag 2048 to 0;2064 to 16

dir=/lustre1/project/stg_00019/research/yan/nanopore_data/sc_repli-g/5_mapped
cd $dir

samtools view -h HG002_sc.trimmed.sorted.bam > HG002_sc.trimmed.sorted.sam

# 注意==用于判断，=用于赋值
awk  'BEGIN{FS=OFS="\t"} {if ($2==2048) {$1=NR; $2=0}}1' HG002_sc.trimmed.sorted.sam>nodup_2048_changed_HG002_sc.trimmed.sorted.sam
awk  'BEGIN{FS=OFS="\t"} {if ($2==2064) {$1=NR; $2=16}}1' nodup_2048_changed_HG002_sc.trimmed.sorted.sam>nodup_2064_2048_changed_HG002_sc.trimmed.sorted.sam

samtools view -Shb nodup_2064_2048_changed_HG002_sc.trimmed.sorted.sam > nodup_flag_changed_HG002_sc.trimmed.sorted.bam
samtools index nodup_flag_changed_HG002_sc.trimmed.sorted.bam

